## ###########################################################################
##
# CentroidsDisplacer.py
##
# Author: Etienne Delclaux
# Created: 17/03/2021 11:15:56 2016 (+0200)
##
# Description:
##
## ###########################################################################


# ToDo: for buffers crossing antimeridian, use a modified CS: "GEOGCRS["WGS 84",
#     DATUM["World Geodetic System 1984",
#         ELLIPSOID["WGS 84",6378137,298.257223563,
#             LENGTHUNIT["metre",1]]],
#     PRIMEM["Greenwich",180,
#         ANGLEUNIT["degree",0.0174532925199433]],
#     CS[ellipsoidal,2],
#         AXIS["geodetic latitude (Lat)",north,
#             ORDER[1],
#             ANGLEUNIT["degree",0.0174532925199433]],
#         AXIS["geodetic longitude (Lon)",east,
#             ORDER[2],
#             ANGLEUNIT["degree",0.0174532925199433]],
#     USAGE[
#         SCOPE["unknown"],
#         AREA["World"],
#         BBOX[-90,-180,90,180]]]"

import math
import random
import typing

from qgis.core import *  # QGIS3
from qgis.PyQt.QtCore import QVariant
from datetime import datetime

from . import Utils

from .Transforms import Transforms
from .Logger import Logger

## #############################################################
# Centroids Displacer
## #############################################################


class CentroidsBufferLayerWriter():
    """ Handle the centroids displacement.
        The existing centroids are available through a map layer.
    """

    def __init__(self):
        self.__generatedLayers = {}  # layer collection for centroids dispalcement

        self.maxDistances = None

    def writerCentroidsBufferLayer(self) -> typing.NoReturn:
        """ Facade method that handle all the centroids displacement.
        """
        Logger.logInfo("[CentroidsBufferLayerWriter] Centroids displacement starts at {}".format(datetime.now()))

        self.clearLayers()

        if not self.maxDistances:
            return

        centroidLayer = Utils.getLayerIfExists(Utils.LayersType.CENTROIDS)

        # create layer for anonymised buffers
        self.__generatedLayers[Utils.LayersType.CENTROIDS_BUFFERS] = Utils.createLayer('Polygon?crs='+Transforms.layer_proj, Utils.LayersType.CENTROIDS_BUFFERS, [
            QgsField("cluster", QVariant.Int),
            QgsField("buf_dist", QVariant.Int)
        ])

        # Displace points
        for centroid_ft in centroidLayer.getFeatures():
            id = centroid_ft['cluster']
            dist = self.maxDistances[id]

            buffer_geom_tmp = QgsGeometry(centroid_ft.geometry())        # transform copy of the centroid into Web Mercator
            buffer_geom_tmp.transform(Transforms.tr)

            # create buffers around centroids
            buffer_geom = buffer_geom_tmp.buffer(dist, 20)

            buffer_geom.transform(Transforms.tr_back)

            centroid_buffer_ft = QgsFeature()
            centroid_buffer_ft.setGeometry(buffer_geom)
            centroid_buffer_ft.setAttributes([
                id,
                dist
            ])

            self.__generatedLayers[Utils.LayersType.CENTROIDS_BUFFERS].dataProvider().addFeatures([centroid_buffer_ft])

        QgsProject.instance().addMapLayer(self.__generatedLayers[Utils.LayersType.CENTROIDS_BUFFERS])

        Utils.writeLayerIfExists(Utils.LayersType.CENTROIDS_BUFFERS)
        Utils.putLayerOnTopIfExists(Utils.LayersType.DISPLACEDANON)  # fix z order
        Utils.putLayerOnTopIfExists(Utils.LayersType.DISPLACED)  # fix z order
        Utils.putLayerOnTopIfExists(Utils.LayersType.LINKS)  # fix z order
        Utils.putLayerOnTopIfExists(Utils.LayersType.CENTROIDS)  # fix z order

        Logger.logInfo("[CentroidsBufferLayerWriter] Centroids displacement finished at {}".format(datetime.now()))

    def clearLayers(self) -> typing.NoReturn:
        """ Clear all the layers of project instance that have been generated by this class
        """
        Utils.removeLayerIfExists(Utils.LayersType.CENTROIDS_BUFFERS)

        self.__generatedLayers.clear()
