# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mics_geocode_plugin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MicsGeocodePluginDialog(object):
    def setupUi(self, MicsGeocodePluginDialog):
        MicsGeocodePluginDialog.setObjectName("MicsGeocodePluginDialog")
        MicsGeocodePluginDialog.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(MicsGeocodePluginDialog)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.runStep1Button = QtWidgets.QPushButton(MicsGeocodePluginDialog)
        self.runStep1Button.setGeometry(QtCore.QRect(90, 100, 93, 28))
        self.runStep1Button.setObjectName("runStep1Button")
        self.runStep2Button = QtWidgets.QPushButton(MicsGeocodePluginDialog)
        self.runStep2Button.setGeometry(QtCore.QRect(200, 100, 93, 28))
        self.runStep2Button.setObjectName("runStep2Button")

        self.retranslateUi(MicsGeocodePluginDialog)
        self.button_box.accepted.connect(MicsGeocodePluginDialog.accept)
        self.button_box.rejected.connect(MicsGeocodePluginDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MicsGeocodePluginDialog)

    def retranslateUi(self, MicsGeocodePluginDialog):
        _translate = QtCore.QCoreApplication.translate
        MicsGeocodePluginDialog.setWindowTitle(_translate("MicsGeocodePluginDialog", "MicsGeocodePlugin"))
        self.runStep1Button.setText(_translate("MicsGeocodePluginDialog", "RunStep1"))
        self.runStep2Button.setText(_translate("MicsGeocodePluginDialog", "RunStep2"))
